# Generated by Django 3.0.8 on 2021-02-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_loanofficer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='registration_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='financeofficer',
            name='signup_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
