# Generated by Django 3.0.8 on 2021-02-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_course_module_moduleitems_survey_surveyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleitems',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='moduleitems',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
