# Generated by Django 3.0.8 on 2021-02-26 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210224_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Algeria', 'Algeria'), ('Angola', 'Angola'), ('Benin', 'Benin'), ('Botswana', 'Botswana'), ('Burkina_Faso', 'Burkina_Faso'), ('Burundi', 'Burundi'), ('Cameroon', 'Cameroon'), ('Cape-Verde', 'Cape-Verde'), ('Central-African-Republic', 'Central-African-Republic'), ('Chad', 'Chad'), ('Camoros', 'Camoros'), ('Democratic-Republic-of-the-Congo', 'Democratic-Republic-of-the-Congo'), ('Djibouti', 'Djibouti'), ('Egypt', 'Egypt'), ('Equatorial-Guinea', 'Equatorial-Guinea'), ('Eritrea', 'Eritrea'), ('Ethiopia', 'Ethiopia'), ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Ghana', 'Ghana'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Ivory-Coast', 'Ivory-Coast'), ('Kenya', 'Kenya'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libya', 'Libya'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Mali', 'Mali'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Namibia', 'Namibia'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Rwanda', 'Rwanda'), ('Sao-Tome-and-Principe', 'Sao-Tome-and-Principe'), ('Senegal', 'Senegal'), ('Seychelles', 'Seychelles'), ('Sierra-Leone', 'Sierra-Leone'), ('Somalia', 'Somalia'), ('South-Africa', 'South-Africa'), ('South-Sudan', 'South-Sudan'), ('Sudan', 'Sudan'), ('Swaziland', 'Swaziland'), ('Tanzania', 'Tanzania'), ('Togo', 'Togo'), ('Tunisia', 'Tunisia'), ('Uganda', 'Uganda'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], default='Zimbabwe', max_length=200)),
                ('official_language', models.TextField(blank=True, null=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='media/images/countries/flags')),
            ],
        ),
        migrations.CreateModel(
            name='NationalBoards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('board_name', models.CharField(blank=True, max_length=70, null=True)),
                ('registered_by_id', models.CharField(blank=True, max_length=70, null=True)),
                ('total_branches', models.IntegerField(blank=True, null=True)),
                ('logo_lg_dn', models.ImageField(blank=True, null=True, upload_to='media/board_images')),
                ('logo_xl_up', models.ImageField(blank=True, null=True, upload_to='media/board_images')),
                ('logo_lg_up', models.ImageField(blank=True, null=True, upload_to='media/board_images')),
                ('hq_city', models.CharField(blank=True, max_length=70, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=70, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('statement', models.TextField(blank=True, null=True)),
                ('acceptPush', models.BooleanField(default=False)),
                ('pushToken', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Country')),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/sacco_images'),
        ),
        migrations.CreateModel(
            name='SACCO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacco_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('affliate_to_NB', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('registered_by_id', models.CharField(blank=True, max_length=70, null=True)),
                ('total_branches', models.IntegerField(blank=True, null=True)),
                ('logo_lg_dn', models.ImageField(blank=True, null=True, upload_to='media/board_images')),
                ('logo_xl_up', models.ImageField(blank=True, null=True, upload_to='media/board_images')),
                ('logo_lg_up', models.ImageField(blank=True, null=True, upload_to='media/board_images')),
                ('city', models.CharField(blank=True, max_length=70, null=True)),
                ('province', models.CharField(blank=True, max_length=70, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=70, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('statement', models.TextField(blank=True, null=True)),
                ('acceptPush', models.BooleanField(default=False)),
                ('pushToken', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Country')),
            ],
        ),
        migrations.CreateModel(
            name='NationalExecutiveBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
                ('valid_till_date', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.NationalBoards')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Department')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.AccountUser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MembershipRole')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Country'),
        ),
    ]
