# Generated by Django 3.0.8 on 2021-02-26 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0001_initial'),
        ('users', '0007_auto_20210226_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalStaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
                ('valid_till_date', models.DateTimeField(auto_now_add=True)),
                ('is_executive', models.BooleanField(default=False, verbose_name='executive')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.NationalBoards')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco.Department')),
            ],
        ),
        migrations.CreateModel(
            name='SaccoStaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
                ('valid_till_date', models.DateTimeField(auto_now_add=True)),
                ('is_executive', models.BooleanField(default=False, verbose_name='executive')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco.Department')),
            ],
        ),
        migrations.RemoveField(
            model_name='clients',
            name='department',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='signing_officer',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lead_tutor',
        ),
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='department',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='client',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='signing_officer',
        ),
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='moduleitems',
            name='module',
        ),
        migrations.RemoveField(
            model_name='nationalboards',
            name='country',
        ),
        migrations.RemoveField(
            model_name='nationalexecutiveboard',
            name='board',
        ),
        migrations.RemoveField(
            model_name='nationalexecutiveboard',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='nationalexecutiveboard',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='nationalexecutiveboard',
            name='role',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='country',
        ),
        migrations.RemoveField(
            model_name='sacco',
            name='country',
        ),
        migrations.RemoveField(
            model_name='surveyitem',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='financeofficer',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='organization',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='sacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SACCO', to='sacco.SACCO', verbose_name='Micro Finance Director'),
        ),
        migrations.AddField(
            model_name='financeofficer',
            name='sacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.SACCO'),
        ),
        migrations.AddField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.Department'),
        ),
        migrations.AddField(
            model_name='manager',
            name='sacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.SACCO'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='sacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.SACCO'),
        ),
        migrations.AddField(
            model_name='student',
            name='sacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.SACCO'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='sacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.SACCO'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.Department'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='ModuleItems',
        ),
        migrations.DeleteModel(
            name='NationalBoards',
        ),
        migrations.DeleteModel(
            name='NationalExecutiveBoard',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='SACCO',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyItem',
        ),
        migrations.AddField(
            model_name='saccostaffmember',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.AccountUser'),
        ),
        migrations.AddField(
            model_name='saccostaffmember',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MembershipRole'),
        ),
        migrations.AddField(
            model_name='saccostaffmember',
            name='sacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.SACCO'),
        ),
        migrations.AddField(
            model_name='nationalstaffmember',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.AccountUser'),
        ),
        migrations.AddField(
            model_name='nationalstaffmember',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MembershipRole'),
        ),
    ]
