# Generated by Django 3.0.8 on 2021-02-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210226_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='department',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='sacco',
        ),
        migrations.RemoveField(
            model_name='nationalstaffmember',
            name='board',
        ),
        migrations.RemoveField(
            model_name='nationalstaffmember',
            name='department',
        ),
        migrations.RemoveField(
            model_name='nationalstaffmember',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='nationalstaffmember',
            name='role',
        ),
        migrations.RemoveField(
            model_name='saccostaffmember',
            name='department',
        ),
        migrations.RemoveField(
            model_name='saccostaffmember',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='saccostaffmember',
            name='role',
        ),
        migrations.RemoveField(
            model_name='saccostaffmember',
            name='sacco',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='sacco',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sacco',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='sacco',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='sacco',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='user_role',
        ),
        migrations.AddField(
            model_name='membershiprole',
            name='group',
            field=models.CharField(choices=[('student', 'student'), ('member', 'member')], default='member', max_length=70),
        ),
        migrations.DeleteModel(
            name='FinanceOfficer',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='NationalStaffMember',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='SaccoStaffMember',
        ),
        migrations.DeleteModel(
            name='Secretary',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
