# Generated by Django 3.0.8 on 2021-02-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210226_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='country',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
