# Generated by Django 3.0.8 on 2021-02-26 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210226_0835'),
        ('sacco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaccoMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.AccountUser')),
                ('sacco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.SACCO')),
            ],
        ),
        migrations.CreateModel(
            name='SaccoStaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
                ('valid_till_date', models.DateTimeField(auto_now_add=True)),
                ('is_executive', models.BooleanField(default=False, verbose_name='executive')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco.Department')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sacco.SaccoMember')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MembershipRole')),
                ('sacco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.SACCO')),
            ],
        ),
        migrations.CreateModel(
            name='NationalStaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
                ('valid_till_date', models.DateTimeField(auto_now_add=True)),
                ('is_executive', models.BooleanField(default=False, verbose_name='executive')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.NationalBoards')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco.Department')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.AccountUser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MembershipRole')),
            ],
        ),
    ]
