# Generated by Django 3.0.8 on 2021-02-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0002_nationalstaffmember_saccomember_saccostaffmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Algeria', 'Algeria'), ('Angola', 'Angola'), ('Benin', 'Benin'), ('Botswana', 'Botswana'), ('Burkina_Faso', 'Burkina_Faso'), ('Burundi', 'Burundi'), ('Cameroon', 'Cameroon'), ('Cape-Verde', 'Cape-Verde'), ('Central-African-Republic', 'Central-African-Republic'), ('Chad', 'Chad'), ('Camoros', 'Camoros'), ('Democratic-Republic-of-the-Congo', 'Democratic-Republic-of-the-Congo'), ('Djibouti', 'Djibouti'), ('Egypt', 'Egypt'), ('Equatorial-Guinea', 'Equatorial-Guinea'), ('Eritrea', 'Eritrea'), ('Ethiopia', 'Ethiopia'), ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Ghana', 'Ghana'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Ivory-Coast', 'Ivory-Coast'), ('Kenya', 'Kenya'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libya', 'Libya'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Mali', 'Mali'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Namibia', 'Namibia'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Rwanda', 'Rwanda'), ('Sao-Tome-and-Principe', 'Sao-Tome-and-Principe'), ('Senegal', 'Senegal'), ('Seychelles', 'Seychelles'), ('Sierra-Leone', 'Sierra-Leone'), ('Somalia', 'Somalia'), ('South-Africa', 'South-Africa'), ('South-Sudan', 'South-Sudan'), ('Sudan', 'Sudan'), ('Swaziland', 'Swaziland'), ('Tanzania', 'Tanzania'), ('Togo', 'Togo'), ('Tunisia', 'Tunisia'), ('Uganda', 'Uganda'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], default='Zimbabwe', max_length=200)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_state', models.CharField(blank=True, max_length=200, null=True)),
                ('official_language', models.TextField(blank=True, null=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='media/images/countries/flags')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.Country')),
            ],
        ),
    ]
