# Generated by Django 3.0.8 on 2021-03-07 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0005_article_articlecomment_articlecommentresponse_articlerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.SACCO'),
        ),
    ]
