# Generated by Django 3.1.4 on 2021-03-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0012_auto_20210307_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='likes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
