# Generated by Django 3.1.4 on 2021-03-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0013_articlecomment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='likes',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
    ]
