# Generated by Django 3.1.4 on 2021-03-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0014_auto_20210307_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('title', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
