# Generated by Django 3.1.4 on 2021-03-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_accountuser_country'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.accountuser'),
        ),
    ]
