# Generated by Django 3.1.4 on 2021-03-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0015_objective'),
        ('web', '0002_testimonial_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.TextField(blank=True, null=True)),
                ('video_title', models.TextField(blank=True, null=True)),
                ('video_subtitle', models.TextField(blank=True, null=True)),
                ('objective', models.ManyToManyField(to='sacco.Objective')),
            ],
        ),
        migrations.DeleteModel(
            name='HomePageObjectives',
        ),
    ]
