# Generated by Django 3.1.4 on 2021-03-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0015_objective'),
        ('web', '0003_auto_20210307_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagefacts',
            name='testimonial',
        ),
        migrations.AddField(
            model_name='homepagefacts',
            name='facts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.facts'),
        ),
        migrations.AlterField(
            model_name='homepagearticle',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.article'),
        ),
        migrations.CreateModel(
            name='HomePageTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.testimonial')),
            ],
        ),
    ]
